// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqSaDSHY9v_AFfx1au7RU6jrn55Fp9D50',
    appId: '1:985003574720:android:f4503509a44c652d6b7425',
    messagingSenderId: '985003574720',
    projectId: 'farma-friend-503a1',
    storageBucket: 'farma-friend-503a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1POLdtc9X5XH0W4mkIfzhrQeikPnd-ZA',
    appId: '1:985003574720:ios:eec168fbaa63a4a96b7425',
    messagingSenderId: '985003574720',
    projectId: 'farma-friend-503a1',
    storageBucket: 'farma-friend-503a1.firebasestorage.app',
    iosBundleId: 'com.example.farmaFriend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgTB9UemnsbbbLE0BpNyCh-F3k-SxxsA0',
    appId: '1:985003574720:web:b44b03022b9783f06b7425',
    messagingSenderId: '985003574720',
    projectId: 'farma-friend-503a1',
    authDomain: 'farma-friend-503a1.firebaseapp.com',
    storageBucket: 'farma-friend-503a1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgTB9UemnsbbbLE0BpNyCh-F3k-SxxsA0',
    appId: '1:985003574720:web:35eb104d3a66b6826b7425',
    messagingSenderId: '985003574720',
    projectId: 'farma-friend-503a1',
    authDomain: 'farma-friend-503a1.firebaseapp.com',
    storageBucket: 'farma-friend-503a1.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1POLdtc9X5XH0W4mkIfzhrQeikPnd-ZA',
    appId: '1:985003574720:ios:eec168fbaa63a4a96b7425',
    messagingSenderId: '985003574720',
    projectId: 'farma-friend-503a1',
    storageBucket: 'farma-friend-503a1.firebasestorage.app',
    iosBundleId: 'com.example.farmaFriend',
  );

}